# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.version.version)

2.3.5


In [22]:
def numpy_info(arr):
    print("\nThe dimension is:", arr.ndim)
    print("The shape is:", arr.shape)
    print("The size is:", arr.size)

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [26]:
### [your code here]
a = np.random.random((2, 3, 5))
print(a)
print(numpy_info(a))

[[[0.23963201 0.67415984 0.84420096 0.05644283 0.04397707]
  [0.48076212 0.83791665 0.17784221 0.90355126 0.73005183]
  [0.76285963 0.2505453  0.5751116  0.43280075 0.61285577]]

 [[0.12293095 0.06089701 0.14867631 0.97585944 0.20469758]
  [0.69307038 0.92709402 0.3061559  0.06735791 0.68167059]
  [0.89050754 0.11581849 0.85455703 0.88165723 0.78859061]]]

The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30
None


In [117]:
a2 = np.random.random_sample((2, 3, 5))
print(a2)
print(numpy_info(a2))

[[[0.50400942 0.04741262 0.67129907 0.39917557 0.12883993]
  [0.47275798 0.2504615  0.83541861 0.22876742 0.98751676]
  [0.9278696  0.56749198 0.06514264 0.32288472 0.68299127]]

 [[0.503311   0.27493252 0.2830201  0.81590494 0.94659941]
  [0.26009934 0.68043453 0.31470858 0.59708304 0.10875625]
  [0.58860166 0.58628066 0.69397338 0.54901445 0.68758691]]]

The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30
None


In [116]:
rng = np.random.default_rng()
a3 = rng.random((2, 3, 5))
print(a3)
print(numpy_info(a3))

[[[0.21402932 0.78027663 0.72901373 0.16007995 0.74739615]
  [0.24880521 0.57747779 0.32012306 0.08754021 0.84934278]
  [0.73550322 0.79289146 0.87727827 0.2171052  0.32765703]]

 [[0.40022279 0.09002499 0.52005157 0.22231725 0.3934552 ]
  [0.16021861 0.38016943 0.22354817 0.1195311  0.58716541]
  [0.96341054 0.74924324 0.49327358 0.79068684 0.40762624]]]

The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30
None



### 4. Print a.


In [21]:
### [your code here]
print(a)

[[[0.91399666 0.4095252  0.41756504 0.37868559 0.29426304]
  [0.61316456 0.93040833 0.54370423 0.6433375  0.71986782]
  [0.24108178 0.35705164 0.17181524 0.99640776 0.93744006]]

 [[0.01872328 0.6313182  0.67551418 0.64103846 0.53224666]
  [0.18966945 0.75131966 0.17782803 0.89147162 0.49250635]
  [0.3598732  0.98738    0.02136735 0.87863006 0.24750485]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [128]:
### [your code here]
b = np.ones((5, 2, 3))



### 6. Print b.


In [30]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [31]:
print(numpy_info(b))


The dimension is: 3
The shape is: (5, 2, 3)
The size is: 30
None



### 7. Do a and b have the same size? How do you prove that in Python code?


In [33]:
### [your code here]
#They do, and to prove it we compare the size of each array using .size function
a.size == b.size

True


### 8. Are you able to add a and b? Why or why not?


In [130]:
### [your code here]
# We can't add a and b because they have different shapes a(2, 3, 5) and b(5, 2, 3), even though they are the same size
# Proof
if a.shape == b.shape:
    result = a + b
else:
    print("Cannot add arrays with different shapes.")

Cannot add arrays with different shapes.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [96]:
### [your code here]
# We have to state the order in which we want to transpose our data.
c = np.transpose(b, (1, 2, 0))
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [97]:
c.shape

(2, 3, 5)

In [131]:
# ALternative: use .reshape t modify the shape without losing data
c2 = np.reshape(b, (2, 3, 5))
print(c2)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [132]:
c2.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
# This now works because array c was transposed to match array a's shape before adding.

d = a + c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
print(a)
print("*****")
print(d)

# c was created by adding a + c, in which a is a random generation of an array and c is a reshaping of b, which is an ONEs array.
# Each index of c is equivalent to the random generated number of a + 1 from the .ones array from b and c.


[[[0.23963201 0.67415984 0.84420096 0.05644283 0.04397707]
  [0.48076212 0.83791665 0.17784221 0.90355126 0.73005183]
  [0.76285963 0.2505453  0.5751116  0.43280075 0.61285577]]

 [[0.12293095 0.06089701 0.14867631 0.97585944 0.20469758]
  [0.69307038 0.92709402 0.3061559  0.06735791 0.68167059]
  [0.89050754 0.11581849 0.85455703 0.88165723 0.78859061]]]
*****
[[[1.23963201 1.67415984 1.84420096 1.05644283 1.04397707]
  [1.48076212 1.83791665 1.17784221 1.90355126 1.73005183]
  [1.76285963 1.2505453  1.5751116  1.43280075 1.61285577]]

 [[1.12293095 1.06089701 1.14867631 1.97585944 1.20469758]
  [1.69307038 1.92709402 1.3061559  1.06735791 1.68167059]
  [1.89050754 1.11581849 1.85455703 1.88165723 1.78859061]]]



### 12. Multiply a and c. Assign the result to e.


In [55]:
### [your code here]
e = a * c



### 13. Does e equal to a? Why or why not?


In [57]:
### [your code here]
#a is equal to e considering all values from c are 1, so to get e we multiply a by 1.
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [82]:
### [your code here]
d_max = np.max(d)
print(f"The maximum value of d is {d_max}.")

d_min = np.min(d)
print(f"The minimum value of d is {d_min}.")

d_mean = np.mean(d)
print(f"The mean value of d is {d_mean}.")



The maximum value of d is 1.9758594414248547.
The minimum value of d is 1.0439770736382996.
The mean value of d is 1.5114083610964513.



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [118]:
### [your code here]
f = np.empty((2, 3, 5))
f.shape

(2, 3, 5)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [133]:
### [your code here]
# We have to iterate through every dimension and compare each individual psitin (i, j, k)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100

print(f)

[[[ 25.  75.  75.  25.   0.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  25.  25. 100.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  75.]]]


In [ ]:
# Alternative approach

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100

print(f)

[[[ 25.  75.  75.  25.   0.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  25.  25. 100.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [122]:
### [your code here]
print(d)
print("***")
print(f)
#Yes, the f is as expected

[[[1.23963201 1.67415984 1.84420096 1.05644283 1.04397707]
  [1.48076212 1.83791665 1.17784221 1.90355126 1.73005183]
  [1.76285963 1.2505453  1.5751116  1.43280075 1.61285577]]

 [[1.12293095 1.06089701 1.14867631 1.97585944 1.20469758]
  [1.69307038 1.92709402 1.3061559  1.06735791 1.68167059]
  [1.89050754 1.11581849 1.85455703 1.88165723 1.78859061]]]
***
[[[ 25.  75.  75.  25.   0.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  25.  25. 100.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [125]:
### [your code here]
g = np.empty((2, 3, 5), dtype=object)
g.shape

(2, 3, 5)

In [108]:
for l in range(f.shape[0]):
    for m in range(f.shape[1]):
        for n in range(f.shape[2]):
            if f[l, m, n] == 0:
                g[l, m, n] = "A"
            elif f[l, m, n] == 25:
                g[l, m, n] = "B"
            elif f[l, m, n] == 50:
                g[l, m, n] = "C"
            elif f[l, m, n] == 75:
                g[l, m, n] = "D"
            else:
                g[l, m, n] = "E"

print(g)

[[['B' 'D' 'D' 'B' 'A']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'B' 'D' 'B' 'D']]

 [['B' 'B' 'B' 'E' 'B']
  ['D' 'D' 'B' 'B' 'D']
  ['D' 'B' 'D' 'D' 'D']]]


In [ ]:
#Alternative approach
g[(f == 0)] = "A"
g[(f == 25)] = "B"
g[(f == 50)] = "C"
g[(f == 75)] = "D"
g[(f == 100)] = "E"

print(g)

[[['B' 'D' 'D' 'B' 'A']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'B' 'D' 'B' 'D']]

 [['B' 'B' 'B' 'E' 'B']
  ['D' 'D' 'B' 'B' 'D']
  ['D' 'B' 'D' 'D' 'D']]]
